#!/bin/bash

#
 # 
 #  Copyright (c) 2011
 #  name : mhogo mchungu
 #  email: mhogomchungu@gmail.com
 #  This program is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation, either version 3 of the License, or
 #  (at your option) any later version.
 #
 #  This program is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.
 #
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #

echo "****************************"
echo "start test"
echo "****************************"

plain="/tmp/testing plain"

luks="/tmp/testing luks"

mount_point="/tmp/testing of volumes"

passphrase="all your pinguins are belong to us"

passphrase1="all your pinguin's pinguins are belong to us"

passfile="/tmp/passfile"

echo -n $passphrase > $passfile

mkdir /tmp/ 1>/dev/null 2>&1

echo ""
echo "creating mount point \"$mount_point\""
mkdir "$mount_point"

echo ""

echo "creating a plain file \"$plain\""

dd if=/dev/zero of="$plain" bs=1024 count=10K 2>/dev/null 1>&2

echo "creating a luks file \"$luks\""

dd if=/dev/zero of="$luks" bs=1024 count=10K 2>/dev/null 1>&2

echo ""

echo "creating a plain volume"

zuluCrypt-cli -c -k -d "$plain" -z ext4 -t plain -p "$passphrase" -g /dev/urandom

sleep 1
echo ""
echo "opening \"$plain\" volume using passphrase"

zuluCrypt-cli -o -d "$plain" -m "$mount_point"/plain -e rw -p "$passphrase"

sleep 1
echo ""
echo "closing \"$plain\" volume"

zuluCrypt-cli -q -d "$plain"

sleep 1
echo ""
echo "opening \"$plain\" volume using keyfile"

zuluCrypt-cli -o -d "$plain" -m "$mount_point"/plain -e rw -f "$passfile"

sleep 1
echo ""
echo "closing \"$plain\" volume"

zuluCrypt-cli -q -d "$plain"
sleep 1
echo ""
echo "creating a luks volume"

zuluCrypt-cli -c -k -d "$luks" -z ext4 -t luks -p "$passphrase" -g /dev/urandom

sleep 1
echo ""
echo "opening \"$luks\" volume using passphrase"

zuluCrypt-cli -o -d "$luks" -m "$mount_point"/luks -e rw -p "$passphrase"

sleep 1
echo ""
echo "closing \"$luks\" volume"

zuluCrypt-cli -q -d "$luks"

sleep 1
echo ""
echo "opening \"$luks\" volume using keyfile"

zuluCrypt-cli -o -d "$luks" -m "$mount_point"/luks -e rw -f "$passfile"

sleep 1
echo ""
echo "closing \"$luks\""
zuluCrypt-cli -q -d "$luks"

sleep 1
echo ""
echo "check keys slots in use"

zuluCrypt-cli -b -d "$luks"

sleep 1
echo ""
echo "add key to luks volume using passphrase and passphrase"

zuluCrypt-cli -a -d "$luks" -y "$passphrase" -l "$passphrase1"

sleep 1
echo ""
echo "add key to luks volume using keyfile and keyfile"

zuluCrypt-cli -a -d "$luks" -u "$passfile" -n "$passfile"

sleep 1
echo ""
echo "add key to luks volume using passphrase and keyfile"

zuluCrypt-cli -a -d "$luks" -y "$passphrase" -n "$passfile"

sleep 1
echo ""
echo "add key to luks volume using keyfile and passphrase"

zuluCrypt-cli -a -d "$luks" -u "$passfile" -l "$passphrase1"

sleep 1
echo ""
echo "check keys slots in use"

zuluCrypt-cli -b -d "$luks"

sleep 1
echo ""
echo "remove added key using a passphrase"

zuluCrypt-cli -r -d "$luks" -p "$passphrase"

sleep 1
echo ""
echo "remove added key using a keyfile"

zuluCrypt-cli -r -d "$luks" -f "$passfile"

sleep 1
echo ""
echo "check keys slots in use"

zuluCrypt-cli -b -d "$luks"

sleep 1
echo "deleting testing files"
rm -rf "$plain"
rm -rf "$luks"
rm -rf "$passfile"

echo "deleting mount point \"$mount_point\""
rmdir "$mount_point"

echo ""
echo "check to see if there are any undeleted zuluCrypt-xxx mappers"

t=`ls /dev/mapper/* | grep zuluCrypt`

if [ "$t" == "" ] ; then
	echo "all mappers are deleted, good"
else
	echo "some mappers remain, bad"
	echo "remaining mappers are:"
	echo "$t"
fi
	
echo "****************************"
echo "end test"
echo "****************************"	


