#!/bin/bash
 
path=$2
 
if [ "$path" == "" ] ; then
	 path="/usr"
fi

if [ "$1" == "install" ] ; then
	cp -vf  zuluCrypt-cli/zuluCrypt-cli /usr/bin
	
	cp -vf zuluCrypt-cli/zuluCrypt.h $path/include
	
	chmod u+s -v $path/bin/zuluCrypt-cli
	
	cp -vf zuluCrypt $path/bin
	
	cp -vf zuluCrypt.desktop $path/share/applications
	
	chmod 755 $path/share/applications/zuluCrypt.desktop
	
	chown root:root $path/share/applications/zuluCrypt.desktop
	
	cp -fv zuluCrypt.png /usr/share/icons
	
	cp -vf libzuluCrypt.so $path/lib
	
	cp -vf libzuluCrypt.so.1.0 $path/lib
	
	cp -vf libzuluCrypt.a $path/libpaths
	
	ldconfig
	
elif [ "$1" == "uninstall" ] ; then
	
	rm -rfv $path/share/icons/zuluCrypt.png
	
	rm -rfv $path/bin/zuluCrypt
	
	rm -rfv $path/bin/zuluCrypt-cli
	
	rm -rfv $path/share/applications/zuluCrypt.desktop
	
	rm -rfv $path/include/zuluCrypt.h
	
	rm -rfv $path/lib/libzuluCrypt.so.1
	
	rm -rfv $path/lib/libzuluCrypt.so
	
	rm -rfv $path/lib/libzuluCrypt.a
	
else		
	cd zuluCrypt-cli
	
	gcc -c -Wall -o String.o String.c
 
	gcc  -D_FILE_OFFSET_BITS=64 -Wall -c libzuluCrypt.c -o libzuluCrypt.o String.o
	
	ar  rcs  libzuluCrypt.a libzuluCrypt.o
	
	gcc -shared -Wl,-soname,libzuluCrypt.so.1 -o libzuluCrypt.so.1.0 libzuluCrypt.o  -lc
 
	ln -sf libzuluCrypt.so.1.0 libzuluCrypt.so
	
	libpaths="-L. -L/lib -L/usr/lib -L/usr/local/lib"
	
	gcc -D_FILE_OFFSET_BITS=64 -Wall $libpaths -lzuluCrypt -lcryptsetup zuluCrypt.c -o zuluCrypt-cli

	cd ..
	
	qmake zuluCrypt.pro

	make
fi


