
.TH zuluCrypt-gui 1

.br
.SH NAME
zuluCrypt-gui - Graphical front end for zuluCrypt-cli
.br
.SH SUMMARY
zuluCrypt-gui is a GUI front end to zuluCrypt-cli
.br
copyright: 2011-2013 Ink Francis,mhogomchungu@gmail.com
.br
license  : GPLv2+
.br
options:
.br
-d   path to where a volume to be auto unlocked/mounted is located
.br
-m   tool to use to open a default file manager(default tool is xdg-open)
.br
-e   start the application without showing the GUI
.br
.br
.SH LAST EDIT
Last change: Mon Apr  8 19:59:36 EDT 2013
