#!/bin/bash
 
path=$2
 
if [ "$path" == "" ] ; then
	 path="/usr"
fi

if [ "$1" == "install" ] ; then
	
	cp -vf zuluCrypt-cli /usr/bin

	chmod -v u+s /usr/bin/zuluCrypt-cli
	
	cp -vf libzuluCrypt.so $path/lib
	
	cp -vf libzuluCrypt.so.1.0 $path/lib
	
	cp -vf libzuluCrypt.a $path/lib
	
	ldconfig
	
else	
	libpaths="-L. -L/lib -L/usr/lib -L/usr/local/lib"
	
	gcc -c -Wall -o String.o String.c
 
	gcc  -D_FILE_OFFSET_BITS=64 -Wall $libpaths -lcryptsetup -c libzuluCrypt.c -o libzuluCrypt.o 
	
	ar  rcs  libzuluCrypt.a String.o libzuluCrypt.o 
	
	gcc -shared -Wl,-soname,libzuluCrypt.so.1 $libpaths -lcryptsetup -o libzuluCrypt.so.1.0 libzuluCrypt.o String.o -lc
 
	ln -sf libzuluCrypt.so.1.0 libzuluCrypt.so	
	
	gcc -D_FILE_OFFSET_BITS=64 -Wall $libpaths -lcryptsetup libzuluCrypt.o String.o zuluCrypt.c -o zuluCrypt-cli -ldl
	
fi
